python3 main.py \
       	--exp sample \
	--workers 2  \
	--epochs 50  \
	--start-epoch 0 \
	--batch-size 128 \
	--learning-rate 0.001 \
	--weight-decay 0 \
	--save-freq 1 \
	--print-iter 1 \
	--save-dir noise  \
	--test 0 \
	--test_e4 0 \
	--defense 1 \
	--optimizer adam